{"uuid": "ed37a982-0c38-468d-b134-ef0f3f606425", "children": ["50b8dc7c-2c40-4197-b754-ddce6e40b519"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))\n", "trace": "  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\myDev\\PeiYou_AutoTest\\testcase\\conftest.py\", line 40, in start_appium_desired\n    driver = appium_desired_caps(host, port, system_port)\n  File \"C:\\myDev\\PeiYou_AutoTest\\base\\DesireCaps.py\", line 42, in appium_desired_caps\n    driver = webdriver.Remote('http://%s:%s/wd/hub'%(host,port), desired_caps)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 144, in __init__\n    proxy\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\request.py\", line 72, in request\n    **urlopen_kw)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\request.py\", line 150, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\poolmanager.py\", line 326, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 641, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\util\\retry.py\", line 368, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\packages\\six.py\", line 685, in reraise\n    raise value.with_traceback(tb)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 603, in urlopen\n    chunked=chunked)\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\http\\client.py\", line 1321, in getresponse\n    response.begin()\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\http\\client.py\", line 296, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\http\\client.py\", line 257, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\wendy chen\\AppData\\Local\\Programs\\Python\\Python37\\lib\\socket.py\", line 589, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1595054063452, "stop": 1595054076719}], "start": 1595054063452, "stop": 1595054077260}